services:
  api:
    build:
      target: staging
    ports:
      - "8000:9000"
    environment:
      APP_ENV: staging
      APP_DEBUG: "true"
      APP_URL: https://staging.taskmanager.com
      CORS_ALLOWED_ORIGINS: "https://staging.taskmanager.com"

  web:
    build:
      target: staging
    ports:
      - "80:80"
