name: task-manager

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: task-manager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d task-manager"]
      interval: 5s
      retries: 5

  api:
    build:
      context: ../api
      dockerfile: ../docker/api/Dockerfile
      additional_contexts:
        docker-context: ./api
    environment:
      APP_NAME: TaskManager
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: task-manager
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: ../web
      dockerfile: ../docker/web/Dockerfile
      additional_contexts:
        docker-context: ./web
    depends_on:
      - api

volumes:
  postgres_data:
